# Generated by Django 3.2.5 on 2022-02-24 12:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('shop', '0003_auto_20220224_1806'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='user',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ManyToManyField(blank=True, null=True, related_name='categories', to='base.Shop'),
        ),
    ]
