# Generated by Django 3.2.5 on 2022-02-25 10:15

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0001_initial'),
        ('shop', '0004_auto_20220224_1809'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='category',
            name='shop',
        ),
        migrations.AddField(
            model_name='category',
            name='shop',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categories', to='base.shop'),
        ),
    ]
