# Generated by Django 3.2.5 on 2022-03-14 08:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220311_1509'),
        ('shop', '0014_alter_product_shop'),
    ]

    operations = [
        migrations.CreateModel(
            name='StockFile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('price_column_name', models.CharField(max_length=40)),
                ('stock_column_name', models.CharField(max_length=40)),
                ('name_column_name', models.CharField(max_length=40)),
                ('stock_file', models.FileField(upload_to='shop/static/stockfiles')),
                ('shop', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='stockfile', to='base.shop')),
            ],
        ),
    ]
