# Generated by Django 3.2.5 on 2022-03-14 13:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0015_stockfile'),
    ]

    operations = [
        migrations.AddField(
            model_name='stockfile',
            name='code_column_name',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
    ]
