# Generated by Django 3.2.5 on 2022-03-15 13:08

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0016_stockfile_code_column_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='code',
            field=models.IntegerField(blank=True, null=True),
        ),
    ]
