# Generated by Django 3.2.5 on 2022-04-17 11:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0025_alter_slide_img'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='index',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
