# Generated by Django 3.2.5 on 2022-04-24 17:25

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0026_product_index'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='supplier',
            field=models.CharField(blank=True, choices=[('Supplier1', 'sup1'), ('Supplier2', 'sup2'), ('Supplier3', 'sup3'), ('Supplier4', 'sup4'), ('Supplier5', 'sup5')], max_length=100, null=True),
        ),
    ]
