# Generated by Django 3.2.5 on 2022-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0028_auto_20220425_2248'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='img',
            field=models.ImageField(blank=True, null=True, upload_to='static/products'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='address',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AddField(
            model_name='supplier',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='static/suppliers'),
        ),
        migrations.AddField(
            model_name='supplier',
            name='phone',
            field=models.CharField(default=1122334455, max_length=10),
            preserve_default=False,
        ),
    ]
