# Generated by Django 3.2.5 on 2022-04-30 12:11

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('shop', '0029_auto_20220430_1254'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='supplier',
            name='pfp',
        ),
    ]
