# Generated by Django 3.2.5 on 2022-05-22 15:31

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_shop_phone'),
        ('shop', '0030_remove_supplier_pfp'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='category',
            unique_together={('name', 'shop')},
        ),
    ]
