# Generated by Django 3.2.5 on 2022-03-03 13:41

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0002_auto_20220303_1723'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
    ]
