# Generated by Django 3.2.5 on 2022-03-03 13:42

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0003_remove_user_shop'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='shop',
            field=models.OneToOneField(blank=True, default=None, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='shop', to='base.shop'),
        ),
    ]
