# Generated by Django 3.2.5 on 2022-03-11 09:39

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0005_notifications'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user',
            name='shop',
        ),
        migrations.AlterField(
            model_name='shop',
            name='user',
            field=models.OneToOneField(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='shop', to=settings.AUTH_USER_MODEL),
        ),
    ]
