# Generated by Django 3.2.5 on 2022-04-30 07:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0006_auto_20220311_1509'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='phone',
            field=models.CharField(default=1122334455, max_length=10),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='shop',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='static/shops'),
        ),
        migrations.AlterField(
            model_name='user',
            name='email',
            field=models.CharField(blank=True, max_length=40, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='pfp',
            field=models.ImageField(blank=True, null=True, upload_to='static/users'),
        ),
    ]
