# Generated by Django 3.2.5 on 2022-05-18 12:21

from django.db import migrations
import phonenumber_field.modelfields


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0009_shop_address'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=phonenumber_field.modelfields.PhoneNumberField(blank=True, max_length=128, null=True, region=None),
        ),
    ]
