# Generated by Django 3.2.5 on 2022-05-18 12:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0010_alter_shop_phone'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='phone',
            field=models.BigIntegerField(blank=True, null=True),
        ),
    ]
