# Generated by Django 3.2.5 on 2022-06-01 13:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0013_alter_shop_phone'),
    ]

    operations = [
        migrations.AddField(
            model_name='shop',
            name='rzp_pb_key',
            field=models.CharField(default='rzp_test_0ovBWEVK2aFRht', max_length=200),
        ),
        migrations.AddField(
            model_name='shop',
            name='rzp_pr_key',
            field=models.CharField(default='omFNDCkZBgjorzpFzNNmfKyd', max_length=200),
        ),
    ]
