# Generated by Django 3.2.5 on 2022-06-03 09:56

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('base', '0014_auto_20220601_1839'),
    ]

    operations = [
        migrations.AlterField(
            model_name='shop',
            name='rzp_pb_key',
            field=models.CharField(default='rzp_test_0ovBWEVK2aFRht', max_length=400),
        ),
        migrations.AlterField(
            model_name='shop',
            name='rzp_pr_key',
            field=models.CharField(default='omFNDCkZBgjorzpFzNNmfKyd', max_length=400),
        ),
    ]
